In [21]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"C:\Users\Adithya\Downloads\student_satisfaction_academic_performance_dataset.csv")

In [2]:
print(df)

    Student_ID  Age  Gender Year_of_Study  Department  Study_Hours_Per_Day  \
0         S001   24  Female      4th Year         ECE                  4.7
1         S002   22  Female      4th Year          IT                  1.3
2         S003   21  Female      2nd Year       Civil                  5.4
3         S004   19    Male      1st Year  Mechanical                  0.5
4         S005   20    Male      2nd Year         CSE                  2.6
..         ...  ...     ...           ...         ...                  ...
115       S116   21  Female      3rd Year          IT                  4.4
116       S117   21    Male      2nd Year       Civil                  2.7
117       S118   20  Female      1st Year         CSE                  4.3
118       S119   22  Female      3rd Year          IT                  0.9
119       S120   20  Female      1st Year         EEE                  2.1

     Attendance_Percentage  CGPA Extracurricular_Participation  \
0                     88.0  8.38                         Often
1                     64.6  7.50                        Rarely
2                     88.3  8.51                     Sometimes
3                     64.7  6.23                         Often
4                     62.5  6.78                     Sometimes
..                     ...   ...                           ...
115                   76.0  8.33                     Sometimes
116                   74.9  7.27                     Sometimes
117                   92.6  8.11                        Rarely
118                   45.0  6.50                    Very often
119                   75.1  8.45                         Never

    AI_Usage_Frequency  ... Teaching_Quality Course_Content Faculty_Support  \
0               Rarely  ...                4              3               3
1            Sometimes  ...                3              4               3
2               Rarely  ...                4              4               3
3               Rarely  ...                4              5               3
4            Sometimes  ...                4              2               4
..                 ...  ...              ...            ...             ...
115              Never  ...                3              5               4
116             Rarely  ...                4              2               4
117         Very often  ...                5              5               3
118         Very often  ...                4              2               3
119              Often  ...                3              5               5

     Learning_Resources  Infrastructure  Placement_Support  \
0                     4               3                  3
1                     4               4                  4
2                     5               4                  3
3                     4               3                  3
4                     4               3                  3
..                  ...             ...                ...
115                   1               2                  3
116                   3               3                  3
117                   4               2                  5
118                   2               3                  3
119                   4               2                  3

     Overall_Satisfaction  Satisfaction_Score  Main_Academic_Challenge  \
0                       4                3.43         Teaching quality
1                       4                3.71          Time management
2                       4                3.86        Academic workload
3                       4                3.71        Academic workload
4                       3                3.29          Time management
..                    ...                 ...                      ...
115                     2                2.86       No major challenge
116                     4                3.29       Financial concerns
117                     4                4.00       Financial concerns
118                     4                3.00        Academic workload
119                     3                3.57         Teaching quality

         Suggested_Improvement
0         More career guidance
1      Improved infrastructure
2      More practical sessions
3      More practical sessions
4         More career guidance
..                         ...
115  Better learning resources
116    Improved infrastructure
117  Better learning resources
118     No specific suggestion
119    More placement training

[120 rows x 23 columns]

In [3]:
df.head()

,Student_ID,Age,Gender,Year_of_Study,Department,Study_Hours_Per_Day,Attendance_Percentage,CGPA,Extracurricular_Participation,AI_Usage_Frequency,...,Teaching_Quality,Course_Content,Faculty_Support,Learning_Resources,Infrastructure,Placement_Support,Overall_Satisfaction,Satisfaction_Score,Main_Academic_Challenge,Suggested_Improvement
0,S001,24,Female,4th Year,ECE,4.7,88.0,8.38,Often,Rarely,...,4,3,3,4,3,3,4,3.43,Teaching quality,More career guidance
1,S002,22,Female,4th Year,IT,1.3,64.6,7.50,Rarely,Sometimes,...,3,4,3,4,4,4,4,3.71,Time management,Improved infrastructure
2,S003,21,Female,2nd Year,Civil,5.4,88.3,8.51,Sometimes,Rarely,...,4,4,3,5,4,3,4,3.86,Academic workload,More practical sessions
3,S004,19,Male,1st Year,Mechanical,0.5,64.7,6.23,Often,Rarely,...,4,5,3,4,3,3,4,3.71,Academic workload,More practical sessions
4,S005,20,Male,2nd Year,CSE,2.6,62.5,6.78,Sometimes,Sometimes,...,4,2,4,4,3,3,3,3.29,Time management,More career guidance

In [5]:
df.shape

(120, 23)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 23 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Student_ID                     120 non-null    str
 1   Age                            120 non-null    int64
 2   Gender                         120 non-null    str
 3   Year_of_Study                  120 non-null    str
 4   Department                     120 non-null    str
 5   Study_Hours_Per_Day            120 non-null    float64
 6   Attendance_Percentage          120 non-null    float64
 7   CGPA                           120 non-null    float64
 8   Extracurricular_Participation  120 non-null    str
 9   AI_Usage_Frequency             120 non-null    str
 10  AI_Tools_Used                  120 non-null    str
 11  Main_AI_Purpose                120 non-null    str
 12  AI_Improves_Learning           120 non-null    str
 13  Teaching_Quality               120 non-null    int64
 14  Course_Content                 120 non-null    int64
 15  Faculty_Support                120 non-null    int64
 16  Learning_Resources             120 non-null    int64
 17  Infrastructure                 120 non-null    int64
 18  Placement_Support              120 non-null    int64
 19  Overall_Satisfaction           120 non-null    int64
 20  Satisfaction_Score             120 non-null    float64
 21  Main_Academic_Challenge        120 non-null    str
 22  Suggested_Improvement          120 non-null    str
dtypes: float64(4), int64(8), str(11)
memory usage: 21.7 KB

In [7]:
df.describe()

,Age,Study_Hours_Per_Day,Attendance_Percentage,CGPA,Teaching_Quality,Course_Content,Faculty_Support,Learning_Resources,Infrastructure,Placement_Support,Overall_Satisfaction,Satisfaction_Score
count,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000
mean,20.950000,2.910833,74.717500,7.884333,3.575000,3.350000,3.650000,3.216667,3.250000,3.108333,3.325000,3.353333
std,1.952589,1.082775,11.904026,0.637421,0.876035,0.940677,0.784835,0.927483,0.822478,0.896265,0.675657,0.340055
min,18.000000,0.500000,45.000000,6.230000,2.000000,1.000000,2.000000,1.000000,1.000000,1.000000,2.000000,2.570000
25%,19.000000,2.100000,66.150000,7.477500,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.140000
50%,21.000000,2.850000,75.000000,7.860000,4.000000,3.000000,4.000000,3.000000,3.000000,3.000000,3.000000,3.430000
75%,23.000000,3.600000,80.900000,8.362500,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,3.570000
max,24.000000,5.400000,100.000000,10.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,4.140000

In [8]:
df.columns

Index(['Student_ID', 'Age', 'Gender', 'Year_of_Study', 'Department',
       'Study_Hours_Per_Day', 'Attendance_Percentage', 'CGPA',
       'Extracurricular_Participation', 'AI_Usage_Frequency', 'AI_Tools_Used',
       'Main_AI_Purpose', 'AI_Improves_Learning', 'Teaching_Quality',
       'Course_Content', 'Faculty_Support', 'Learning_Resources',
       'Infrastructure', 'Placement_Support', 'Overall_Satisfaction',
       'Satisfaction_Score', 'Main_Academic_Challenge',
       'Suggested_Improvement'],
      dtype='str')

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.isnull().sum()

Student_ID                       0
Age                              0
Gender                           0
Year_of_Study                    0
Department                       0
Study_Hours_Per_Day              0
Attendance_Percentage            0
CGPA                             0
Extracurricular_Participation    0
AI_Usage_Frequency               0
AI_Tools_Used                    0
Main_AI_Purpose                  0
AI_Improves_Learning             0
Teaching_Quality                 0
Course_Content                   0
Faculty_Support                  0
Learning_Resources               0
Infrastructure                   0
Placement_Support                0
Overall_Satisfaction             0
Satisfaction_Score               0
Main_Academic_Challenge          0
Suggested_Improvement            0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df = df.drop_duplicates()

In [13]:
df.isnull().sum()

Student_ID                       0
Age                              0
Gender                           0
Year_of_Study                    0
Department                       0
Study_Hours_Per_Day              0
Attendance_Percentage            0
CGPA                             0
Extracurricular_Participation    0
AI_Usage_Frequency               0
AI_Tools_Used                    0
Main_AI_Purpose                  0
AI_Improves_Learning             0
Teaching_Quality                 0
Course_Content                   0
Faculty_Support                  0
Learning_Resources               0
Infrastructure                   0
Placement_Support                0
Overall_Satisfaction             0
Satisfaction_Score               0
Main_Academic_Challenge          0
Suggested_Improvement            0
dtype: int64

In [14]:
df["Department"].unique()

<StringArray>
['ECE', 'IT', 'Civil', 'Mechanical', 'CSE', 'EEE']
Length: 6, dtype: str

In [15]:
df["Gender"].unique()

<StringArray>
['Female', 'Male']
Length: 2, dtype: str

In [16]:
df["AI_Usage_Frequency"].unique()

<StringArray>
['Rarely', 'Sometimes', 'Very often', 'Often', 'Never']
Length: 5, dtype: str

In [18]:
df["Study_Category"] = pd.cut(
    df["Study_Hours_Per_Day"],
    bins=[0, 1, 3, 5, 10],
    labels=["Low", "Moderate", "High", "Very High"]
)

In [19]:
df["Attendance_Category"] = pd.cut(
    df["Attendance_Percentage"],
    bins=[0, 60, 75, 85, 100],
    labels=["Low", "Average", "Good", "Excellent"]
)

In [20]:
df["Performance_Category"] = pd.cut(
    df["CGPA"],
    bins=[0, 6, 7.5, 8.5, 10],
    labels=["Low", "Average", "Good", "Excellent"]
)